/**
 * 预置术语包（en=zh 单向，模型可自动反查推断反向译法，故无需存双向）
 *
 * 选词纪律（真机实测驱动，务必遵守）：
 *  1. 优先多词组合：多义词（patch/bond/thread/yield）单独出现时若被注入，会把
 *     本来正确的译文改坏（实测 "patch the leak" → "进行补丁处理"），故一律用多词限定，
 *     如 security patch / corporate bond / thread pool / bond yield。
 *  2. 避开日常高频词：temperature（气温）、epoch（纪元）、consideration（考虑）、
 *     cell（牢房/细胞）、branch（树枝）等裸词不收。
 *  3. 只用无歧义的专业词：hypertension、myocardial infarction 这类日常不出现的词可裸用。
 *  4. 术语只在文本命中时才注入（见 preload matchTerms），所以词条多是安全的，
 *     危险的是"命中不该命中的文本"。
 */
export const TERM_PACKS = [
  {
    id: 'ai',
    name: 'AI / 大模型',
    terms: {
      // 模型与架构
      'large language model': '大语言模型',
      'transformer': '变换器',
      'attention mechanism': '注意力机制',
      'self-attention': '自注意力',
      'multi-head attention': '多头注意力',
      'encoder': '编码器',
      'decoder': '解码器',
      'neural network': '神经网络',
      'convolutional neural network': '卷积神经网络',
      'recurrent neural network': '循环神经网络',
      'feedforward network': '前馈网络',
      'embedding': '嵌入',
      'positional encoding': '位置编码',
      'layer normalization': '层归一化',
      'activation function': '激活函数',
      'mixture of experts': '混合专家',
      'foundation model': '基础模型',
      'diffusion model': '扩散模型',
      'multimodal': '多模态',
      // 训练与优化
      'pre-training': '预训练',
      'fine-tuning': '微调',
      'instruction tuning': '指令微调',
      'reinforcement learning': '强化学习',
      'supervised learning': '监督学习',
      'unsupervised learning': '无监督学习',
      'transfer learning': '迁移学习',
      'few-shot learning': '少样本学习',
      'zero-shot': '零样本',
      'in-context learning': '上下文学习',
      'chain of thought': '思维链',
      'gradient descent': '梯度下降',
      'backpropagation': '反向传播',
      'loss function': '损失函数',
      'learning rate': '学习率',
      'batch size': '批大小',
      'overfitting': '过拟合',
      'underfitting': '欠拟合',
      'regularization': '正则化',
      'dataset': '数据集',
      'ground truth': '真值',
      'data annotation': '数据标注',
      'training data': '训练数据',
      // 推理与部署
      'inference': '推理',
      'tokenizer': '分词器',
      'context window': '上下文窗口',
      'KV cache': 'KV 缓存',
      'speculative decoding': '投机解码',
      'quantization': '量化',
      'knowledge distillation': '知识蒸馏',
      'model pruning': '模型剪枝',
      'model checkpoint': '模型检查点',
      'model serving': '模型服务',
      'throughput': '吞吐量',
      'latency': '延迟',
      // 应用与评测
      'prompt engineering': '提示词工程',
      'system prompt': '系统提示词',
      'retrieval augmentation': '检索增强',
      'vector database': '向量数据库',
      'semantic search': '语义搜索',
      'knowledge graph': '知识图谱',
      'AI agent': 'AI 智能体',
      'benchmark dataset': '基准数据集',
      'hallucination': '幻觉',
      'perplexity': '困惑度',
      // 安全与对齐
      'AI safety': 'AI 安全',
      'jailbreak': '越狱',
      'guardrails': '护栏',
      'red teaming': '红队测试',
      'speech recognition': '语音识别',
      'text-to-speech': '语音合成',
      'text-to-image': '文生图',
    },
  },
  {
    id: 'dev',
    name: '编程开发',
    terms: {
      // 数据结构与算法
      'hash table': '哈希表',
      'linked list': '链表',
      'binary tree': '二叉树',
      'data structure': '数据结构',
      'binary search': '二分查找',
      'sorting algorithm': '排序算法',
      'time complexity': '时间复杂度',
      'space complexity': '空间复杂度',
      'recursion': '递归',
      'iteration': '迭代',
      'hash function': '哈希函数',
      // 缺陷与调试
      'memory leak': '内存泄漏',
      'race condition': '竞态条件',
      'deadlock': '死锁',
      'stack overflow': '栈溢出',
      'buffer overflow': '缓冲区溢出',
      'null pointer': '空指针',
      'memory allocation': '内存分配',
      'breakpoint': '断点',
      'debugger': '调试器',
      'stack trace': '堆栈跟踪',
      'error handling': '错误处理',
      'exception handling': '异常处理',
      // 语言与范式
      'compiler': '编译器',
      'runtime': '运行时',
      'refactor': '重构',
      'polymorphism': '多态',
      'encapsulation': '封装',
      'inheritance': '继承',
      'abstraction': '抽象',
      'design pattern': '设计模式',
      'dependency injection': '依赖注入',
      'regular expression': '正则表达式',
      'garbage collection': '垃圾回收',
      'serialization': '序列化',
      'deserialization': '反序列化',
      'concurrency': '并发',
      'parallel processing': '并行处理',
      'asynchronous': '异步',
      'callback function': '回调函数',
      'code snippet': '代码片段',
      'boilerplate': '样板代码',
      // 工程与协作
      'unit test': '单元测试',
      'integration test': '集成测试',
      'test coverage': '测试覆盖率',
      'code review': '代码审查',
      'code style': '代码风格',
      'pull request': '拉取请求',
      'merge conflict': '合并冲突',
      'version control': '版本控制',
      'continuous integration': '持续集成',
      'continuous deployment': '持续部署',
      // 系统与运维
      'thread pool': '线程池',
      'thread safety': '线程安全',
      'load balancing': '负载均衡',
      'microservice': '微服务',
      'containerization': '容器化',
      'virtual machine': '虚拟机',
      'command line': '命令行',
      'shell script': 'Shell 脚本',
      'environment variable': '环境变量',
      'configuration file': '配置文件',
      'API endpoint': 'API 端点',
      'request header': '请求头',
      'response body': '响应体',
      'status code': '状态码',
      'deploy': '部署',
      'rollback': '回滚',
      'system monitoring': '系统监控',
      'scalability': '可扩展性',
      'message queue': '消息队列',
      'distributed system': '分布式系统',
    },
  },
  {
    id: 'med',
    name: '医学',
    terms: {
      // 疾病
      'hypertension': '高血压',
      'hypotension': '低血压',
      'diabetes': '糖尿病',
      'cardiovascular disease': '心血管疾病',
      'myocardial infarction': '心肌梗死',
      'arrhythmia': '心律失常',
      'atherosclerosis': '动脉粥样硬化',
      'thrombosis': '血栓形成',
      'embolism': '栓塞',
      'edema': '水肿',
      'anemia': '贫血',
      'leukemia': '白血病',
      'carcinoma': '癌',
      'tumor': '肿瘤',
      'malignant': '恶性',
      'benign': '良性',
      'metastasis': '转移',
      'autoimmune disease': '自身免疫性疾病',
      'chronic disease': '慢性病',
      'infectious disease': '传染病',
      'comorbidity': '合并症',
      // 症状与体征
      'symptom': '症状',
      'syndrome': '综合征',
      'lesion': '病变',
      'inflammation': '炎症',
      'infection': '感染',
      'nausea': '恶心',
      'blood pressure': '血压',
      'heart rate': '心率',
      'blood sugar': '血糖',
      'cholesterol': '胆固醇',
      // 诊疗
      'diagnosis': '诊断',
      'prognosis': '预后',
      'biopsy': '活检',
      'clinical trial': '临床试验',
      'placebo': '安慰剂',
      'anesthesia': '麻醉',
      'surgery': '手术',
      'incision': '切口',
      'suture': '缝合',
      'dosage': '剂量',
      'prescription': '处方',
      'side effect': '副作用',
      'adverse reaction': '不良反应',
      'contraindication': '禁忌症',
      'chemotherapy': '化疗',
      'radiotherapy': '放疗',
      'rehabilitation': '康复',
      'palliative care': '姑息治疗',
      // 检查
      'computed tomography': '计算机断层扫描',
      'magnetic resonance imaging': '磁共振成像',
      'ultrasound': '超声',
      'electrocardiogram': '心电图',
      'endoscopy': '内窥镜检查',
      'blood test': '血液检查',
      // 生理与药物
      'immune system': '免疫系统',
      'immune response': '免疫反应',
      'antibiotic': '抗生素',
      'antibiotic resistance': '抗生素耐药性',
      'vaccine': '疫苗',
      'antibody': '抗体',
      'antigen': '抗原',
      'platelet': '血小板',
      'white blood cell': '白细胞',
      'red blood cell': '红细胞',
      'hemoglobin': '血红蛋白',
      'hormone': '激素',
      'insulin': '胰岛素',
      'metabolism': '新陈代谢',
      'cell membrane': '细胞膜',
      'genetic mutation': '基因突变',
      'pathogen': '病原体',
      'chronic fatigue': '慢性疲劳',
      // 公卫
      'epidemiology': '流行病学',
      'incidence rate': '发病率',
      'prevalence': '患病率',
      'mortality rate': '死亡率',
    },
  },
  {
    id: 'fin',
    name: '金融',
    terms: {
      // 权益与固收
      'equity market': '股票市场',
      'corporate bond': '公司债券',
      'government bond': '国债',
      'bond market': '债券市场',
      'bond yield': '债券收益率',
      'dividend yield': '股息率',
      'yield curve': '收益率曲线',
      'stock split': '股票拆分',
      'share buyback': '股份回购',
      'market capitalization': '市值',
      'earnings per share': '每股收益',
      'price-to-earnings ratio': '市盈率',
      'initial public offering': '首次公开募股',
      'prospectus': '招股说明书',
      // 衍生品
      'call option': '看涨期权',
      'put option': '看跌期权',
      'futures contract': '期货合约',
      'forward contract': '远期合约',
      'interest rate swap': '利率掉期',
      'bull spread': '牛市价差',
      'bear spread': '熊市价差',
      'financial derivative': '金融衍生品',
      'hedging strategy': '对冲策略',
      'hedge fund': '对冲基金',
      'short selling': '卖空',
      'margin requirement': '保证金要求',
      'margin call': '追加保证金',
      'collateral': '抵押品',
      // 市场与行情
      'bull market': '牛市',
      'bear market': '熊市',
      'volatility': '波动率',
      'market liquidity': '市场流动性',
      'arbitrage': '套利',
      'exchange rate': '汇率',
      'recession': '经济衰退',
      'quantitative easing': '量化宽松',
      'risk premium': '风险溢价',
      // 财务与报表
      'balance sheet': '资产负债表',
      'income statement': '利润表',
      'cash flow': '现金流',
      'accounts receivable': '应收账款',
      'accounts payable': '应付账款',
      'depreciation': '折旧',
      'amortization': '摊销',
      'gross margin': '毛利率',
      'net profit': '净利润',
      'operating expense': '营业费用',
      'working capital': '营运资金',
      'valuation': '估值',
      'credit rating': '信用评级',
      'default risk': '违约风险',
      // 投资与政策
      'investment portfolio': '投资组合',
      'asset allocation': '资产配置',
      'diversification': '分散投资',
      'asset management': '资产管理',
      'wealth management': '财富管理',
      'index fund': '指数基金',
      'mutual fund': '共同基金',
      'exchange-traded fund': '交易型开放式指数基金',
      'compound interest': '复利',
      'interest rate': '利率',
      'inflation': '通货膨胀',
      'deflation': '通货紧缩',
      'monetary policy': '货币政策',
      'fiscal policy': '财政政策',
      'central bank': '中央银行',
      'sovereign debt': '主权债务',
      'trade deficit': '贸易逆差',
      'foreign exchange reserves': '外汇储备',
      'underwriter': '承销商',
    },
  },
  {
    id: 'law',
    name: '法律',
    terms: {
      // 合同基础
      'force majeure': '不可抗力',
      'breach of contract': '违约',
      'termination clause': '终止条款',
      'liquidated damages': '违约金',
      'indemnity': '赔偿',
      'warranty': '担保',
      'contracting party': '缔约方',
      'governing law': '管辖法律',
      'null and void': '无效',
      'representations and warranties': '陈述与保证',
      'covenants': '承诺条款',
      'material adverse change': '重大不利变化',
      'specific performance': '强制履行',
      'reasonable efforts': '合理努力',
      'best efforts': '最大努力',
      'non-disclosure agreement': '保密协议',
      'confidentiality': '保密',
      'due diligence': '尽职调查',
      'power of attorney': '授权委托书',
      'severability': '可分割性',
      'waiver': '弃权',
      'addendum': '附录',
      // 主体与权属
      'intellectual property': '知识产权',
      'trademark infringement': '商标侵权',
      'copyright holder': '版权所有者',
      'patent application': '专利申请',
      'trade secret': '商业秘密',
      'lien': '留置权',
      'mortgage': '抵押',
      'pledge agreement': '质押协议',
      'guarantor': '保证人',
      'assignee': '受让人',
      'fiduciary duty': '信义义务',
      'limited liability': '有限责任',
      'legal entity': '法律实体',
      // 诉讼
      'plaintiff': '原告',
      'defendant': '被告',
      'tort': '侵权',
      'jurisdiction': '管辖权',
      'arbitration': '仲裁',
      'litigation': '诉讼',
      'class action': '集体诉讼',
      'statute of limitations': '诉讼时效',
      'affidavit': '宣誓书',
      'subpoena': '传票',
      'deposition': '证言笔录',
      'testimony': '证词',
      'verdict': '裁决',
      'summary judgment': '简易判决',
      'notice of appeal': '上诉通知',
      'settlement agreement': '和解协议',
      'punitive damages': '惩罚性赔偿',
      'compensatory damages': '补偿性赔偿',
      // 合规与监管
      'regulatory compliance': '合规',
      'antitrust': '反垄断',
      'consumer protection': '消费者保护',
      'data privacy': '数据隐私',
      'terms of service': '服务条款',
      'privacy policy': '隐私政策',
      'fair use': '合理使用',
      'escrow': '托管',
      'closing condition': '交割条件',
    },
  },
]
