/**
 * 预置术语包（en=zh 单向，模型可自动反查推断反向译法，故无需存双向）
 * 选词原则：优先多词/生僻专业词，避开 process/cache/merge 这类日常高频词，
 * 避免术语全局生效时把普通文本误锁（术语对全部语向生效，见设置页说明）。
 */
export const TERM_PACKS = [
  {
    id: 'ai',
    name: 'AI / 大模型',
    terms: {
      'large language model': '大语言模型',
      'transformer': '变换器',
      'attention mechanism': '注意力机制',
      'fine-tuning': '微调',
      'inference': '推理',
      'embedding': '嵌入',
      'tokenizer': '分词器',
      'token': '词元',
      'prompt': '提示词',
      'benchmark': '基准测试',
      'hallucination': '幻觉',
      'quantization': '量化',
      'knowledge distillation': '知识蒸馏',
      'overfitting': '过拟合',
      'dataset': '数据集',
      'checkpoint': '检查点',
      'agent': '智能体',
      'context window': '上下文窗口',
      'retrieval augmentation': '检索增强',
      'multimodal': '多模态',
      'reinforcement learning': '强化学习',
      'neural network': '神经网络',
      'gradient descent': '梯度下降',
      'ground truth': '真值',
    },
  },
  {
    id: 'dev',
    name: '编程开发',
    terms: {
      'memory leak': '内存泄漏',
      'race condition': '竞态条件',
      'deadlock': '死锁',
      'unit test': '单元测试',
      'code review': '代码审查',
      'hash table': '哈希表',
      'linked list': '链表',
      'data structure': '数据结构',
      'binary search': '二分查找',
      'time complexity': '时间复杂度',
      'regular expression': '正则表达式',
      'dependency injection': '依赖注入',
      'garbage collection': '垃圾回收',
      'stack overflow': '栈溢出',
      'breakpoint': '断点',
      'debugger': '调试器',
      'compiler': '编译器',
      'recursion': '递归',
      'refactor': '重构',
      'deploy': '部署',
      'serialization': '序列化',
      'concurrency': '并发',
      'polymorphism': '多态',
      'pull request': '拉取请求',
      'version control': '版本控制',
    },
  },
  {
    id: 'med',
    name: '医学',
    terms: {
      'hypertension': '高血压',
      'diabetes': '糖尿病',
      'inflammation': '炎症',
      'biopsy': '活检',
      'diagnosis': '诊断',
      'prognosis': '预后',
      'symptom': '症状',
      'lesion': '病变',
      'metastasis': '转移',
      'anesthesia': '麻醉',
      'placebo': '安慰剂',
      'antibiotic': '抗生素',
      'platelet': '血小板',
      'myocardial infarction': '心肌梗死',
      'clinical trial': '临床试验',
      'side effect': '副作用',
      'immune system': '免疫系统',
      'blood pressure': '血压',
      'syndrome': '综合征',
      'pathogen': '病原体',
      'chronic disease': '慢性病',
      'computed tomography': '计算机断层扫描',
    },
  },
  {
    id: 'fin',
    name: '金融',
    terms: {
      'bull spread': '牛市价差',
      'call option': '看涨期权',
      'put option': '看跌期权',
      'futures contract': '期货合约',
      'equity': '股权',
      'bond': '债券',
      'yield': '收益率',
      'hedging': '对冲',
      'liquidity': '流动性',
      'arbitrage': '套利',
      'dividend': '股息',
      'initial public offering': '首次公开募股',
      'margin requirement': '保证金要求',
      'volatility': '波动率',
      'portfolio': '投资组合',
      'derivative': '衍生品',
      'interest rate': '利率',
      'inflation': '通货膨胀',
      'asset allocation': '资产配置',
      'market capitalization': '市值',
      'short selling': '卖空',
      'exchange rate': '汇率',
    },
  },
  {
    id: 'law',
    name: '法律',
    terms: {
      'force majeure': '不可抗力',
      'tort': '侵权',
      'plaintiff': '原告',
      'defendant': '被告',
      'jurisdiction': '管辖权',
      'arbitration': '仲裁',
      'indemnity': '赔偿',
      'breach of contract': '违约',
      'intellectual property': '知识产权',
      'confidentiality': '保密',
      'warranty': '担保',
      'contracting party': '缔约方',
      'statute of limitations': '诉讼时效',
      'due diligence': '尽职调查',
      'power of attorney': '授权委托书',
      'non-disclosure agreement': '保密协议',
      'governing law': '管辖法律',
      'null and void': '无效',
      'termination clause': '终止条款',
      'liquidated damages': '违约金',
    },
  },
]
